# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hehung's Blog
subtitle: '生命不息 折腾不止'
description: 'hehung的博客，本人从事嵌入式开发工作，主要分享个人的经历。'
keywords: ['单片机', 'FreeRTOS', 'STM32', 'NPX', 'GD32', '嵌入式']
author: hehung
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://hehung.top
root: /
#permalink: :year/:month/:day/:title/
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing index.html from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 6
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-matery-master

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    -github: git@github.com:hehung/hehung.github.io.git,master
#    -gitee: https://gitee.com/hehung/blog.git,master
    -coding: git@git.coding.net:hehung/hehung.git,master
  #branch: master

# hexo-filter-github-emojis 表情可以动作
githubEmojis:
  enable: true
  className: github-emoji
  inject: true
  styles:
  customEmojis:

# hexo-prism-plugin 代码高亮
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess 
  theme: 'default'
  line_number: false    # default false 
  custom_css:     # optional

# hexo-generator-search 搜索
search:
  path: search.xml
  field: post

# hexo-permalink-pinyin 中文连接转拼音，因为中文不利于SEO
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'

# hexo-wordcount 文章字数统计插件
wordCount:
  enable: true # 将这个值设置为 true 即可.
  postWordCount: true
  min2read: true
  totalCount: true

# hexo-generator-feed RSS
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

# hexo-lazyload-image 懒加载, 不好用
lazyload:
  enable: false
  onlypost: true  # 是否只对文章的图片做懒加载
  loadingImg: /medias/loading.gif # eg ./images/loading.gif









